User.create!(email: "test@example.com", password: "password", first_name: "Testy", last_name: "Testerson", years_xp: 2, victor_scale: "V3", font_scale: "5.9", description: "I like Cheese", location: "CT")
User.create!(email: "alan@example.com", password: "password", first_name: "Alan", last_name: "Barton", years_xp: 7, victor_scale: "V6", font_scale: "5.11", description: "I live to climb", location: "RI")

Image.create!(user_id: 1, image_url: "image1.url")
Image.create!(user_id: 1, image_url: "image2.url")
Image.create!(user_id: 2, image_url: "image3.url")
Image.create!(user_id: 2, image_url: "image4.url")

ClimbingStyle.create!(user_id: 1, climbing_type: "bouldering")
ClimbingStyle.create!(user_id: 1, climbing_type: "sport")
ClimbingStyle.create!(user_id: 2, climbing_type: "bouldering")
ClimbingStyle.create!(user_id: 2, climbing_type: "sport")
ClimbingStyle.create!(user_id: 2, climbing_type: "trad")

Message.create!(sender_id: 1, reciever_id: 2, message: "Hello Alan")
Message.create!(sender_id: 2, reciever_id: 1, message: "Hey testy")
Message.create!(sender_id: 1, reciever_id: 2, message: "How was your day")
Message.create!(sender_id: 2, reciever_id: 1, message: "It was good")
Message.create!(sender_id: 1, reciever_id: 2, message: "do any climbing?")
Message.create!(sender_id: 2, reciever_id: 1, message: "no been pretty busy")
Message.create!(sender_id: 2, reciever_id: 1, message: "What about you?")
Message.create!(sender_id: 1, reciever_id: 2, message: "no but ill probably go later")
Message.create!(sender_id: 1, reciever_id: 2, message: "want to join?")
Message.create!(sender_id: 2, reciever_id: 1, message: "sure")
Message.create!(sender_id: 2, reciever_id: 1, message: "What time?")
Message.create!(sender_id: 1, reciever_id: 2, message: "8ish?")
Message.create!(sender_id: 2, reciever_id: 1, message: "sounds good")
Message.create!(sender_id: 1, reciever_id: 2, message: "see you there")
